pipeline:
  build:
    image: node:9.2
    commands:
      - npm install
  publish:
    app: hex.maelphick.com
    when:
      branch: master
    image: appleboy/drone-ssh
    host: maelphick.com
    username: mael
    port: 22
    secrets: [ ssh_password  ]
    script:
      - cd sites/friendagon
      - echo "Pulling latest changes"
      - git pull
      - echo "Running npm install"
      - npm i
      - echo "Linting"
      - npm run lint
      - echo "Building bundle"
      - npm run build
      - echo "Restarting service"
      - sudo systemctl restart friendagon
      - echo "Finished"
